### ISSUE TITLE
Page prints at 100% in spite of scaling set

### ISSUE THREAD

**Issue by quinnat** [bdcomp/PrintPreview#1]
Hello. First of all, thanks for this great addon! The following may be, I think, an issue with the operating system and not your Firefox extension. But I wanted to mention it because it may save others some frustration. (BTW, this issue existed with the extension published by Patrick Lauke also.)

#### My setup:
 * Firefox version: 57 (Developer Edition)
 * Print/Print Preview Context version: 0.9
 * Operating System: Mac OS X 10.10.5

#### Steps to reproduce the problem:
Right-click a web page to print
Choose "Print/Print Preview" > "Print Preview" from context menu
Change page scale to something other than 100%
Click "Print" button at top-left
In the Mac OS print dialog box, observe page scaling to see if it matches 

#### What you expected to happen:
The page scaling should be what was selected in the Print Preview interface

#### What actually happened:
Pages were being printed at 100% when I had changed scaling to something else.

#### My workaround:
I decided to choose a different printer in the Mac OS print dialog and the scaling changed to the percentage I wanted. I noticed that I could "fix" the problem by choosing the "Default Settings" preset instead of "Last Used Settings".

Hope this makes sense!   :-)

**Comment by bdcomp** [comment]
Hi,

Thanks for your kind words, I am happy to hear that you like this extension.

As this extension:
1. Only opens 2 print dialogs (no parameters or etc.) and 
2. Written from scratch as WE

Your issue is probably related to CUPS.
