### ISSUE TITLE
Could you add Save as PDF to the menu?

### ISSUE THREAD

**Issue by jscher2000** [bdcomp/PrintPreview#3]
Not sure whether it is in scope, but the built-in method should be pretty easy to implement (setting aside translations and icons...): 

* https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/tabs/saveAsPDF

I don't know how best to handle MacOS where it isn't available -- maybe set enabled = false for the menu item, or just don't add it?

* https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/runtime/PlatformOs
* https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/menus/create

**Comment by bdcomp** [comment]
Hi,

Thanks for your detailed suggestion.

In fact, I tried to implement this months ago, but it didn't work. At least not on my Linux system.

I will take another look, though not promising :wink:

**Comment by bdcomp** [comment]
I just uploaded a new version.
Please give it a drive.

P.S. PlatformOs is not working. As of now I included a check via getPlatformInfo, although on my Linux it's "undefined", not sure why...

**Comment by jscher2000** [comment]
Thanks, it largely works (Fx63/Win7x64), but it could be improved. These might be a limitation of the API, or there might be a workaround:

(1) Not integrated with downloads, so there's no confirmation of completion or easy access to the file.

_Found a bug on file for this:_ https://bugzilla.mozilla.org/show_bug.cgi?id=1421410

(2) If a page happens not to have a title, the suggested title is ".pdf"

_I mentioned it in this bug, which is directed toward letting the extension developer pass in a file name:_ https://bugzilla.mozilla.org/show_bug.cgi?id=1483590

So not much we can do about that at the moment.

**Comment by bdcomp** [comment]
The feature is implemented and looks like working for months without any bugs.
Any follow-up that is on my side should be opened as a new issue.

@jscher2000 Thanks again!

**Comment by LC43** [comment]
Hi, was the code merged back to this repo? i wanted to try to understand my issue by looking at the code, but the latest commit is way older.
