### ISSUE TITLE
Version for Firefox 52 ESR?

### ISSUE THREAD

**Issue by mrkapqa** [bdcomp/PrintPreview#4]
Thanks for creating a new issue!

Hello ,

i saw here

https://web.archive.org/web/20180730173046/https://addons.mozilla.org/en-US/firefox/addon/print-print-preview-context/versions/

only for FF56+

is there no version available for FF 52 ESR?

Thank oyu very much

**Comment by bdcomp** [comment]
@mrkapqa The current stable ESR version is 60.4
https://wiki.mozilla.org/Release_Management/Calendar

Firefox 52.X ESR is not supported by Mozilla for many months.
