### ISSUE TITLE
Save as PDF: Upload to Server or Convert in Place?

### ISSUE THREAD

**Issue by GGillan** [bdcomp/PrintPreview#5]
Hi,

Does the Save as PDF feature convert to PDF on my PC or is content uploaded to a server somewhere for conversion? Asking for privacy and security considerations.

**Comment by bdcomp** [comment]
Hi @GGillan
Thanks for your interest in the add-on.

The PDF feature uses the built-in Firefox option:
https://developer.mozilla.org/docs/Mozilla/Add-ons/WebExtensions/API/tabs/saveAsPDF
None uploaded to any server.
